version: '2.0'

services:
  grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
    networks:
      - internal
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      - internal

networks:
  internal:
